# NumPy Tutorial👨🏼‍🏫

The goal of this repository is to provide an introduction in NumPy library. This library is used for working with arrays in domain of linear algebra, Fourier Transform and matrices.

**Why use NumPy?**🕵🏼

The answer to this question is very simple: Numpy gives us array objects that are much faster than traditional lists. This is because **ndarray** (array object) is stored in a continuous place in memory, unlike lists. Another important aspect is the fact that numpy arrays are containers of items of the same type in contrast to the list which can contain a mix of Python types including strings, floats, booleans, etc

The following exemple confirms our assertion. We calculate the execution time when adding two lists and two arrays. We will compare the results obtained in the two situations.

In [10]:
from time import*
from numpy import*
def add_lists():
    t1=time()
    x=range(10000000)
    y=range(10000000)
    z=[x[i]+y[i] for i in range(len(x))]
    t2=time()
    return t2-t1

def add_arrays():
    t1=time()
    x=arange(10000000)
    y=arange(10000000)
    z=x+y
    t2=time()
    return t2-t1
time_list=add_lists()
time_array=add_arrays()
print("Execution time (lists): ",time_list)
print("Execution time (arrays): ",time_array)
    

Execution time (lists):  4.281202077865601
Execution time (arrays):  0.06110978126525879


The obtained results confirm the fact that arrays are much faster than lists

**Creating Numpy Arrays**✏️

The syntax of arange: _arange(start,stop,step)_

In [11]:
a=arange(1,10)
print(a)#The default value for 'step' is 1
b=arange(1,10,0.5)
print(b)

[1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


A better alternative for the function _arange_ is _linspace_

_The syntax of linspace: linspace(start, stop, num=50, endpoint=True/False)_

Linspace returns an ndarray, consisting of 'num' equally spaced samples in the closed interval [start, stop]. 

In [12]:
print(linspace(1,10,endpoint=True))#50 values between 1 and 10
print(linspace(1,10))#The default value for 'endpoint' is True
print(linspace(1,10,endpoint=False))# excluding the endpoint
print(linspace(1,10,5))#5 values between 1 and 10

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6

**Size of an Arrays in Numpy**✏️

In [13]:
x = array(13)
print("x: ", x)
print("The type of x: ", type(x))
print("The dimension of x:",ndim(x))#Scalars are zero dimensional.

y=arange(1,20,2)
print("y: ", y)
print("The type of y: ", type(y))
print("The dimension of y:",ndim(y))#Vectors are a 1-dimenional. 

z = array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print("z: ", z)
print("The type of z: ", type(z))
print("The dimension of z:",ndim(z))#2-dimenional array. 

x:  13
The type of x:  <class 'numpy.ndarray'>
The dimension of x: 0
y:  [ 1  3  5  7  9 11 13 15 17 19]
The type of y:  <class 'numpy.ndarray'>
The dimension of y: 1
z:  [[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
The type of z:  <class 'numpy.ndarray'>
The dimension of z: 2


**Shape of an Array**✏️

The "shape" function returns a tuple with the number of elements per axis (dimension). In our example, the shape is equal to (5, 3), i.e. we have 5 lines and 3 columns.

In [14]:
z = array([ [7, 63, 87],
               [77, 9, 59],
               [85, 7, 9],
               [79, 72, 71],
               [3, 89, 3]])

print(shape(z))

(5, 3)


The function "shape" can also be used to change the shape of an array.

In [18]:
z.shape=(3,5)
print("z: ",z)
print("The dimension of z: ",shape(z))

z:  [[ 7 63 87 77  9]
 [59 85  7  9 79]
 [72 71  3 89  3]]
The dimension of z:  (3, 5)


**Indexing and Slicing**✏️

Indexing one-dimensional arrays.

In [20]:
v=arange(1,50,3)
print("v: ",v)
print("The first element: ",v[0])
print("The last element: ",v[-1])

v:  [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
The first element:  1
The last element:  49


Indexing multidimensional arrays.

❗️ The first column has index 0. The first row has index 0.

In [23]:
t=array([[1,2,3],
        [0,7,8],
        [4,5,6]])
print("The element in first row and second column: ",t[0][1])

The element in first row and second column:  2


Slicing of a one-dimensional array.

In [32]:
p=array([1,9,0,3,6,7,5])
print("p: ",p)
print(p[0:3])
print(p[2:5])
print(p[:])
print(p[-4:])

p:  [1 9 0 3 6 7 5]
[1 9 0]
[0 3 6]
[1 9 0 3 6 7 5]
[3 6 7 5]


Slicing of multidimensional array.

In [44]:
k=array([[11, 12, 13, 14, 15],
            [21, 22, 23, 24, 25],
            [31, 32, 33, 34, 35],
            [41, 42, 43, 44, 45],
            [51, 52, 53, 54, 55]])
print(k[3:,0:])#the last two rows in the array
print(k[0:1,0:])#the first row in the array
print(k[-1:,0:])#the last row in the array
print(k[1:3,1:3])
print(k[:,4:])#the last column

[[41 42 43 44 45]
 [51 52 53 54 55]]
[[11 12 13 14 15]]
[[51 52 53 54 55]]
[[22 23]
 [32 33]]
[[15]
 [25]
 [35]
 [45]
 [55]]


The reshape function is used to construct the two-dimensional array

In [46]:
Z=arange(12)
print("Z: ",Z)
Z1=Z.reshape(2,6)
print("Z1: ",Z1)
Z2=Z.reshape(3,4)
print("Z2: ",Z2)

Z:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Z1:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Z2:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Zeros method. Ones method. Identity method.**✏️

In [49]:
E=ones((3,3))#create an array with 3 columns and 3 rows and all elements equal to 1
print("E: ",E)
F=zeros((3,2))#create an array with 3 columns and 2 rows and all elements equal to 0
print("F: ",F)
G=identity(4)#create identity array
print("G: ",G)

E:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
F:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
G:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Numerical Operations on Numpy Arrays**✏️

Adding / Subtraction scalars to arrays.

In [52]:
L = array([2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9])
L1= L + 2
print(L1)
L2=L-2
print(L2)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]
[ 0.    1.    5.9   1.3   4.9  -1.89  8.3  10.9 ]


Multiplication / Division / Exponentiation to arrays.

In [55]:
L3 = array([2,3, 7, 3, 6, 0, 10, 12])
print("Multiplication: ",L3*4)
print("Exponentiation: ",L3**2)
print("Division: ",L3/2)

Multiplication:  [ 8 12 28 12 24  0 40 48]
Exponentiation:  [  4   9  49   9  36   0 100 144]
Division:  [1.  1.5 3.5 1.5 3.  0.  5.  6. ]


Arithmetic Operations with two Arrays.

In [62]:
A=zeros((3,3))
B=identity(3)
C=array([[1,2,3],
   [4,5,6],
   [7,8,9]])
D=array([[1,2],
   [0,1],
   [1,5]])
print("Multiplication: ",A*C)#The elements are solely component-wise multiplied.
print("Adding: ",B+C)
print("Matrix Multiplication: ",dot(C,D))#Matrix Multiplication


Multiplication:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Adding:  [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Matrix Multiplication:  [[ 4 19]
 [10 43]
 [16 67]]


"Transpose" method.

In [63]:
print("Transpose of the array: ",D.transpose())

Transpose of the array:  [[1 0 1]
 [2 1 5]]


Boolean Indexing

In [65]:
Q=array([[42,56,89,65],
        [99,88,42,12],
        [55,42,17,18]])
print(Q>10)
R=array([[1,2,3,65],
         [4,5,6,21],
         [7,8,17,18]])
print(Q==R)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False  True  True]]


**A simple application**⚡️

We create a board, which consists of nine buttons stored in a two-dimensional list. When a button is clicked, a random number between (0,1) is generated.

In [134]:
from tkinter import*
from random import*
def function(l,c):
    for i in range(9):    
        b[l][c].configure(text=str(round(random(),3)))

gui=Tk()
gui.title("RandomNumber")
gui.geometry("400x250")
b=[[0,0,0],
   [0,0,0],
   [0,0,0]]
for i in range(3):
    for j in range(3):
        b[i][j]=Button(font=('Verdana',30),width=5,bg='yellow',command=lambda l=i,c=j:function(l,c))
        b[i][j].grid(row=i,column=j)
mainloop()